import { InvitationData, TemplateStyle } from '../types/invitation';

export const TEMPLATES: TemplateStyle[] = [
  {
    id: 'heavenly-blessings',
    name: 'Heavenly Blessings',
    description: 'Soft ivory, celestial baby blue, champagne gold, and delicate baptismal purity.',
    previewColor: '#96B3D6',
    genderAffinity: 'boy',
    theme: {
      primaryColor: '#FFFDF8',
      secondaryColor: '#EBF1F6',
      accentColor: '#C9A96A',
      backgroundColor: '#FAF7F2',
      cardBgColor: '#FFFFFF',
      textColor: '#2E353C',
      subtextColor: '#667482',
      frameShape: 'arch',
      fontHeading: 'cormorant',
      fontScript: 'vibes',
      fontBody: 'montserrat',
    },
  },
  {
    id: 'golden-grace',
    name: 'Golden Grace',
    description: 'Warm ivory, soft beige, and radiant champagne gold for timeless sacred elegance.',
    previewColor: '#C9A96A',
    genderAffinity: 'neutral',
    theme: {
      primaryColor: '#FFFDF8',
      secondaryColor: '#F4EEE5',
      accentColor: '#B8924A',
      backgroundColor: '#F8F4EE',
      cardBgColor: '#FFFFFF',
      textColor: '#2B2621',
      subtextColor: '#736B63',
      frameShape: 'oval',
      fontHeading: 'cormorant',
      fontScript: 'vibes',
      fontBody: 'montserrat',
    },
  },
  {
    id: 'little-princess',
    name: 'Little Princess',
    description: 'Tender dusty rose, warm cream, delicate floral petals, and soft gold shimmer.',
    previewColor: '#DDA8A5',
    genderAffinity: 'girl',
    theme: {
      primaryColor: '#FFFDF9',
      secondaryColor: '#F9ECEB',
      accentColor: '#C49774',
      backgroundColor: '#FAF4F3',
      cardBgColor: '#FFFFFF',
      textColor: '#3A2828',
      subtextColor: '#7F6767',
      frameShape: 'floral',
      fontHeading: 'playfair',
      fontScript: 'parisienne',
      fontBody: 'poppins',
    },
  },
  {
    id: 'enchanted-garden',
    name: 'Enchanted Garden',
    description: 'Organic sage green, pure white baby breath flowers, and gentle olive blessings.',
    previewColor: '#8FA89B',
    genderAffinity: 'neutral',
    theme: {
      primaryColor: '#FCFDFB',
      secondaryColor: '#EDF3EF',
      accentColor: '#B89658',
      backgroundColor: '#F4F7F5',
      cardBgColor: '#FFFFFF',
      textColor: '#26332C',
      subtextColor: '#5E7067',
      frameShape: 'scalloped',
      fontHeading: 'cormorant',
      fontScript: 'vibes',
      fontBody: 'montserrat',
    },
  },
  {
    id: 'little-prince',
    name: 'Little Prince',
    description: 'Powder blue, French vanilla, gold stars, and royal baby milestone charm.',
    previewColor: '#789EC4',
    genderAffinity: 'boy',
    theme: {
      primaryColor: '#FFFDF8',
      secondaryColor: '#E6EFF7',
      accentColor: '#D4AF37',
      backgroundColor: '#F3F7FA',
      cardBgColor: '#FFFFFF',
      textColor: '#1E2D3D',
      subtextColor: '#53687E',
      frameShape: 'arch',
      fontHeading: 'cormorant',
      fontScript: 'vibes',
      fontBody: 'poppins',
    },
  },
  {
    id: 'teddy-bear',
    name: 'Teddy Bear Picnic',
    description: 'Warm honey biscuit, soft ivory, playful teddy, and sweet 1st birthday milestones.',
    previewColor: '#BA8D64',
    genderAffinity: 'neutral',
    theme: {
      primaryColor: '#FFFDF9',
      secondaryColor: '#F5ECE1',
      accentColor: '#A87444',
      backgroundColor: '#FAF5EE',
      cardBgColor: '#FFFFFF',
      textColor: '#33271C',
      subtextColor: '#736050',
      frameShape: 'circle',
      fontHeading: 'playfair',
      fontScript: 'vibes',
      fontBody: 'poppins',
    },
  },
  {
    id: 'pastel-clouds',
    name: 'Angelic Lavender',
    description: 'Soft pastel lavender, angelic cloud motifs, and shimmering starry grace.',
    previewColor: '#B3A1C9',
    genderAffinity: 'girl',
    theme: {
      primaryColor: '#FFFDFE',
      secondaryColor: '#F3EEF8',
      accentColor: '#B89569',
      backgroundColor: '#F7F3FA',
      cardBgColor: '#FFFFFF',
      textColor: '#32253D',
      subtextColor: '#6B5A79',
      frameShape: 'oval',
      fontHeading: 'cormorant',
      fontScript: 'parisienne',
      fontBody: 'montserrat',
    },
  },
  {
    id: 'vintage-rose',
    name: 'Vintage Heirloom',
    description: 'Antique lace ivory, muted rose quartz, and traditional heirloom grace.',
    previewColor: '#C28E8E',
    genderAffinity: 'girl',
    theme: {
      primaryColor: '#FFFEFA',
      secondaryColor: '#F8EFEF',
      accentColor: '#B88F68',
      backgroundColor: '#FAF5F5',
      cardBgColor: '#FFFFFF',
      textColor: '#362424',
      subtextColor: '#785A5A',
      frameShape: 'scalloped',
      fontHeading: 'playfair',
      fontScript: 'vibes',
      fontBody: 'montserrat',
    },
  },
];

export const INITIAL_INVITATION_DATA: InvitationData = {
  // Baby details
  babyName: 'Liam Alexander',
  babyNickname: 'Liam',
  gender: 'boy',
  babyPhotoUrl: '/src/assets/images/baby_baptism_portrait_1791254793568.jpg',
  coverKicker: 'YOU ARE INVITED',
  milestoneTitle: 'Holy Baptism & 1st Birthday',
  introHeading: 'With grateful hearts and immense joy,',
  introText: 'We invite you to celebrate a very special milestone in our little one’s life as he is welcomed into God’s family and turns one year old.',

  // Baptism
  baptismDate: 'Sunday, December 13, 2026',
  baptismTime: '10:00 AM',
  baptismChurch: 'St. Joseph Parish Church',
  baptismAddress: 'MacArthur Highway, Urdaneta City, Pangasinan',
  baptismMapsUrl: 'https://maps.google.com/?q=St.+Joseph+Parish+Church+Urdaneta+City',
  baptismNotes: 'The Sacred Rite begins promptly. Please be seated in prayer by 9:45 AM.',

  // Birthday Reception
  birthdayDate: 'Sunday, December 13, 2026',
  birthdayTime: '12:00 PM',
  birthdayVenue: 'The Garden Events Place',
  birthdayAddress: 'Poblacion, Urdaneta City, Pangasinan',
  birthdayMapsUrl: 'https://maps.google.com/?q=The+Garden+Events+Place+Urdaneta+City',
  birthdayNotes: 'A feast of thanksgiving, sweet cake cutting, joyful laughter, and celebration!',

  // Countdown
  countdownTarget: '2026-12-13T10:00:00',

  // Parents
  fatherName: 'Juan Santos',
  motherName: 'Elena Cruz-Santos',
  parentsMessage: 'Together with our families, we warmly invite you to share in this blessed and joyful celebration.',

  // Godparents
  godparentsHeading: 'Godparents',
  godparentsSubheading: 'Those who will help guide our little one with faith, love, and kindness.',
  godparents: [
    { id: '1', name: 'Maria Santos', role: 'Godmother', relationship: "Aunt" },
    { id: '2', name: 'Juan Dela Cruz', role: 'Godfather', relationship: "Uncle" },
    { id: '3', name: 'Dr. Sofia Morales', role: 'Godmother', relationship: "Family Friend" },
    { id: '4', name: 'Engr. Rafael Reyes', role: 'Godfather', relationship: "Family Friend" },
    { id: '5', name: 'Beatrice Villanueva', role: 'Godmother', relationship: "Godmother" },
    { id: '6', name: 'Gabriel Mendoza', role: 'Godfather', relationship: "Godfather" },
  ],

  // Bible Verse
  verseText: '“Let the little children come to me, and do not hinder them, for the kingdom of heaven belongs to such as these.”',
  verseCitation: 'Matthew 19:14',

  // Birthday section
  birthdayHeading: "Let's Celebrate!",
  birthdaySubheading: 'Our little blessing is turning ONE! 🎂',

  // Photo Gallery
  galleryTitle: 'One Year of Love',
  gallerySubtitle: 'Memories of a wonderful first year filled with milestones, smiles, and grace.',
  photos: [
    {
      id: 'photo-1',
      url: '/src/assets/images/baby_baptism_portrait_1791254793568.jpg',
      caption: 'Blessings & White Heirloom Christening Outfit',
      ageMonth: 'Month 11',
    },
    {
      id: 'photo-2',
      url: '/src/assets/images/baby_sleeping_angel_1791254831082.jpg',
      caption: 'Our peaceful little angel dreaming sweet dreams',
      ageMonth: 'Newborn',
    },
    {
      id: 'photo-3',
      url: '/src/assets/images/baby_teddy_memory_1791254818642.jpg',
      caption: 'Playful giggles with teddy bear companion',
      ageMonth: 'Month 8',
    },
    {
      id: 'photo-4',
      url: '/src/assets/images/baptism_cake_gold_1791254806162.jpg',
      caption: 'Golden leaf 1st celebration cake & white flowers',
      ageMonth: 'Year 1',
    },
  ],

  // Timeline
  timelineItems: [
    {
      id: 'time-1',
      time: '10:00 AM',
      title: 'Holy Sacrament of Baptism',
      subtitle: 'St. Joseph Parish Church',
      icon: 'cross',
    },
    {
      id: 'time-2',
      time: '11:30 AM',
      title: 'Family & Godparent Portraits',
      subtitle: 'Church Courtyard & Altar steps',
      icon: 'camera',
    },
    {
      id: 'time-3',
      time: '12:00 PM',
      title: 'Welcome to Reception',
      subtitle: 'The Garden Events Place Grand Hall',
      icon: 'heart',
    },
    {
      id: 'time-4',
      time: '12:30 PM',
      title: 'Thanksgiving Luncheon & Program',
      subtitle: 'Buffet feast, toasts & milestones slideshow',
      icon: 'utensils',
    },
    {
      id: 'time-5',
      time: '1:30 PM',
      title: 'Cake Blowing & 1st Birthday Games',
      subtitle: 'Balloons, sweet treats & party favors',
      icon: 'cake',
    },
  ],

  // RSVP settings
  rsvpDeadline: 'Please confirm your attendance by Sunday, November 30, 2026',
  rsvpNote: 'Your presence would make this special day even more meaningful to our family.',
  contactNumber: '+63 917 123 4567',

  // Closing
  closingHeading: 'Thank You',
  closingMessage: 'Thank you for being part of our little one’s journey and for celebrating this sacred and joyous milestone with us.',
  closingSignature: 'With love, Juan & Elena',

  // Design default: Heavenly Blessings
  templateId: 'heavenly-blessings',
  frameShape: 'arch',
  fontHeading: 'cormorant',
  fontScript: 'vibes',
  fontBody: 'montserrat',
  primaryColor: '#FFFDF8',
  secondaryColor: '#EBF1F6',
  accentColor: '#C9A96A',
  backgroundColor: '#FAF7F2',
  cardBgColor: '#FFFFFF',
  textColor: '#2E353C',
  subtextColor: '#667482',

  showFloatingPetals: true,
  showSparkles: true,
  musicEnabled: true,
  musicTheme: 'lullaby-harp',
};
